"""Analyze the JS code at the error position and try to fix _sce_dlgtqred."""
import json
from pathlib import Path
from py_mini_racer import MiniRacer

R1_RANDOM = "EmlTWqfjgNExE6ongWjf6w=="
ENCRYPTR_SERVER = "rIsBBcYjaN88Fnj00PlLGQ=="
COPYRIGHT_KEY = "0WZJpdEknsuQl4OoWRlTWSuffXj1MlrSry7j7M+vQc="

JS_FILE = Path(r"C:\Users\Administrator\AppData\Roaming\youku-app\local_caches\static\904ddb4d0e70418993e1854359d9b066.js")


def main():
    js_code = JS_FILE.read_text(encoding="utf-8", errors="replace")

    # Extract context around the error positions
    print("=== JS code around position 15509 (Object.stringify) ===")
    start = max(0, 15509 - 200)
    end = min(len(js_code), 15509 + 200)
    print(f"Chars {start}-{end}:")
    print(js_code[start:end])
    print()

    print("=== JS code around position 11651 (KK function) ===")
    start = max(0, 11651 - 200)
    end = min(len(js_code), 11651 + 200)
    print(f"Chars {start}-{end}:")
    print(js_code[start:end])
    print()

    # Search for "d42hksldla" in the JS
    print("=== Searching for 'd42hksldla' in JS ===")
    idx = js_code.find("d42hksldla")
    if idx >= 0:
        start = max(0, idx - 300)
        end = min(len(js_code), idx + 300)
        print(f"Found at {idx}:")
        print(js_code[start:end])
    else:
        print("Not found as literal string - it's generated by the VM")

    # Search for "oiunb" property
    print("\n=== Searching for 'oiunb' in JS ===")
    idx = js_code.find("oiunb")
    if idx >= 0:
        start = max(0, idx - 300)
        end = min(len(js_code), idx + 300)
        print(f"Found at {idx}:")
        print(js_code[start:end])
    else:
        print("Not found - it's generated by the VM")

    # Search for "jsvmportal" in JS
    print("\n=== Searching for 'jsvmportal' in JS ===")
    for match_start in range(len(js_code)):
        idx = js_code.find("jsvmportal", match_start)
        if idx < 0:
            break
        start = max(0, idx - 100)
        end = min(len(js_code), idx + 200)
        print(f"Found at {idx}:")
        print(js_code[start:end])
        print()
        match_start = idx + 1
        if match_start > idx + 10:
            break

    # Try with patched JSON.stringify that handles everything
    print("\n=== Trying with patched JSON.stringify ===")
    ctx = MiniRacer()

    setup_js = """
    var window = this;
    var self = this;
    var global = this;
    var navigator = { userAgent: 'Mozilla/5.0', platform: 'Win32', language: 'zh-CN' };
    var document = {
        createElement: function() { return { setAttribute: function(){}, appendChild: function(){}, style: {}, getContext: function(){ return null; }, addEventListener: function(){} }; },
        getElementsByTagName: function() { return [{ appendChild: function(){}, addEventListener: function(){} }]; },
        getElementById: function() { return null; },
        body: { appendChild: function(){}, addEventListener: function(){} },
        head: { appendChild: function(){} },
        addEventListener: function(){},
        removeEventListener: function(){},
        cookie: '', referrer: '', title: '', URL: 'https://www.youku.com/', domain: 'youku.com'
    };
    var location = { href: 'https://www.youku.com/', hostname: 'www.youku.com', protocol: 'https:', pathname: '/', search: '', hash: '' };

    // Patched JSON.stringify that handles circular refs, functions, undefined
    var _orig_stringify = JSON.stringify;
    JSON.stringify = function(obj, replacer, space) {
        try {
            return _orig_stringify(obj, function(key, val) {
                if (typeof val === 'function') return '[function]';
                if (typeof val === 'undefined') return null;
                return val;
            }, space);
        } catch(e) {
            // If circular reference, try a simple approach
            try {
                var seen = [];
                return _orig_stringify(obj, function(key, val) {
                    if (typeof val === 'object' && val !== null) {
                        if (seen.indexOf(val) >= 0) return undefined;
                        seen.push(val);
                    }
                    if (typeof val === 'function') return '[function]';
                    if (typeof val === 'undefined') return null;
                    return val;
                }, space);
            } catch(e2) {
                return '{}';
            }
        }
    };

    var console = { log: function(){}, error: function(){}, warn: function(){}, debug: function(){}, info: function(){} };
    var performance = { now: function(){ return Date.now(); }, timing: { navigationStart: 0 } };
    var localStorage = { getItem: function(){ return null; }, setItem: function(){}, removeItem: function(){} };
    var sessionStorage = { getItem: function(){ return null; }, setItem: function(){}, removeItem: function(){} };
    """
    ctx.eval(setup_js)
    ctx.eval(js_code)
    print("JS loaded with patched stringify")

    # Try calling _sce_dlgtqred with patched stringify
    code = f"""
    (function() {{
        var R1 = '{R1_RANDOM}';
        var encryptRServer = '{ENCRYPTR_SERVER}';
        var copyrightKey = '{COPYRIGHT_KEY}';
        try {{
            var key = _sce_dlgtqred(R1, encryptRServer, copyrightKey);
            return JSON.stringify({{
                success: true,
                value: key,
                type: typeof key,
                length: typeof key === 'string' ? key.length : null
            }});
        }} catch(e) {{
            return JSON.stringify({{
                success: false,
                error: e.message,
                stack: e.stack ? e.stack.substring(0, 1000) : null
            }});
        }}
    }})();
    """
    result = ctx.eval(code)
    print(f"Result: {result}")
    result_dict = json.loads(result)
    if result_dict.get('success'):
        print(f"Key: {result_dict['value']}")
        print(f"Type: {result_dict['type']}")
    else:
        print(f"Error: {result_dict['error']}")
        if result_dict.get('stack'):
            print(f"Stack: {result_dict['stack']}")


if __name__ == "__main__":
    main()
